### ISSUE TITLE
Setup header properties on `.graphql` function

### ISSUE THREAD

**Issue by marcogbarcellos** [EasyGraphQL/easygraphql-tester#102]
I was wondering if we have a way to setup header properties through the `.graphql` function. I'm using apollo server and it seems that using it is bypassing some middlewares(like authentication/authorization stuff).

example on what would be nice to have:

```js
tester.graphql(query, undefined, undefined, { isLocal: false, headers: { authorization: 'Bearer JWT AshufewmrgfddJWT_TOKEN_EX' } })
  .then(result => console.log(result))
  .catch(err => console.log(err))

```

**Comment by estrada9166** [comment]
I hadn't try it yet, but maybe you can set on the context a new object with the `req` and also there with the headers. I think that doing that we can mock the request.

[Here](https://blog.apollographql.com/authorization-in-graphql-452b1c402a9) is a post from Apollo that maybe can be useful.

**Comment by estrada9166** [comment]
@marcogbarcellos does it works for you?

Can we close this issue?

**Comment by marcogbarcellos** [comment]
Yeah it worked! thanks!
