### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by RaviGhaghada** [EasyGraphQL/easygraphql-tester#137]
is it?

**Comment by RaviGhaghada** [comment]
r.i.p.

**Comment by estrada9166** [comment]
Sorry the delay, it's not dead, I'm starting to focus back on it, and open for any contribution! 

Thanks!

**Comment by RaviGhaghada** [comment]
You can count me in! I'd love to contribute :)

Currently we're stuck on graphql version 14 and we really need to upgrade it to v15. I've tried doing that but I ran into issues.

Currently, both easygraphql-mock and easygraphql-parser are throwing errors because they're still stuck in graphql v14. We need to upgrade both of them.

I'll get back to you once I have working versions of both of them!

**Comment by estrada9166** [comment]
Awesome! I'll try to work on it this weekend so we can update to GraphQL 15!

**Comment by traviswimer** [comment]
No updates have been published in several years and issues/PRs seem to have been ignored for years.

Unfortunately, I think it's safe to say this project is now very much dead. ☠️

Has some other project overtaken this purpose?
