### ISSUE TITLE
GraphQL 16 support?

### ISSUE THREAD

**Issue by eytanfb** [EasyGraphQL/easygraphql-tester#147]
Hello,

Do you have any plans to have support for GraphQL 16 or a suggested package to replace `easygraphql-tester`?

**Comment by runlevel5** [comment]
at this stage I don't think they do but I reckon you could submit a Pull Request

**Comment by getanish** [comment]
I still don't see support for GraphQL 16. Has this issue been resolved ?
```
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^0.13.0 || ^14.0.0 || ^15.0.0" from easygraphql-tester@6.0.1
```
