### ISSUE TITLE
Performance issue with multiple nested queries and nested tree of queries.

### ISSUE THREAD

**Issue by einaralex** [EasyGraphQL/easygraphql-tester#20]
It took 640 seconds for me to run a single test on my schema.

Every query is rather long, 10-20 item in each and some refrence 1-3 other queries.
I can send my schema in a private message if you need testing data.

It seem to be the worst with nested tree of queries, simplefied example:
```
type Booking {
  id: ID!
  details: [Detail]
}
type Detail {
  dimensions: [Dimension]
}
type Dimension {
  weight: String
}
type Query {
      booking(id: ID!): Booking
}
```

The query I'm using for my test:
```
{
  booking(id:"123456") {
      id
  }
}
```

**Comment by estrada9166** [comment]
@einaralex there is a new version that solve this issue!! update it and check it please...

Also, I just run the test/schema you send to me and this was the result:

```
> jest

 PASS  __tests__/index.test.js
  Test schemas
    Queries
      ✓ Should pass (3ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.078s
Ran all test suites.
```

**Comment by einaralex** [comment]
Amazing, it's lightning fast now! :D Thank you!
