### ISSUE TITLE
'Type "User" not found in document' 

### ISSUE THREAD

**Issue by picklechips** [EasyGraphQL/easygraphql-tester#62]
I've loaded in my schema, but when I run `tester = new EasyGraphQLTester(schemaCode)` I just get an error saying `Type "User" not found in document `

I can't figure out what this means... My schema has no user Type so why does it want it

**Comment by estrada9166** [comment]
@picklechips Thanks for creating this issue!

Can you check please if in any of your Queries/Mutations defined on your GraphQL schema,  it's using the type `User` but it's not defined as a `type`

**Comment by estrada9166** [comment]
@picklechips If it's possible, can you share me your schema, so I can reproduce that error locally?

**Comment by picklechips** [comment]
I was using Prisma and forgot to include the prisma schema, good ol' case of user error!
