### ISSUE TITLE
Support for gql

### ISSUE THREAD

**Issue by renegoretzka** [EasyGraphQL/easygraphql-tester#91]
I would love to use gql tag in the query/mutation to have autocomplete. it works without using resolvers, but when I use resolvers in the tester, I cannot use the gql tag

**Comment by estrada9166** [comment]
@renegoretzka Thanks for creating this issue! I'll deploy soon the new version with the fix

**Comment by estrada9166** [comment]
@renegoretzka The new version has been deployed `v5.1.2`
