### ISSUE TITLE
example does not work

### ISSUE THREAD

**Issue by overpod** [EasyGraphQL/easygraphql-tester#94]
```
'use strict'

const { GraphQLSchema, GraphQLObjectType, GraphQLString } = require('graphql')
const EasyGraphQLTester = require('easygraphql-tester')

const schema = new GraphQLSchema({
    query: new GraphQLObjectType({
        name: 'RootQueryType',
        fields: {
            hello: {
                type: GraphQLString,
                resolve() {
                    return 'world'
                },
            },
        },
    }),
})

const tester = new EasyGraphQLTester(schema)
```
**Error**
```
trofimov@trofimov-PC:~/Documents/projects/openhouse/openh/back-next$ node test.js
/home/trofimov/Documents/projects/openhouse/openh/back-next/node_modules/easygraphql-parser/node_modules/graphql/utilities/buildClientSchema.js:57
  var typeIntrospectionMap = (0, _keyMap.default)(schemaIntrospection.types, function (type) {
                                                                      ^

TypeError: Cannot read property 'types' of undefined
    at buildClientSchema (/home/trofimov/Documents/projects/openhouse/openh/back-next/node_modules/easygraphql-parser/node_modules/graphql/utilities/buildClientSchema.js:57:71)
    at schemaParser (/home/trofimov/Documents/projects/openhouse/openh/back-next/node_modules/easygraphql-parser/lib/schemaParser.js:222:28)
    at new Tester (/home/trofimov/Documents/projects/openhouse/openh/back-next/node_modules/easygraphql-tester/lib/tester.js:28:25)
    at Object.<anonymous> (/home/trofimov/Documents/projects/openhouse/openh/back-next/test.js:20:16)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
```
help me please

**Comment by estrada9166** [comment]
Which version of `GraphQL` are you using?

**Comment by overpod** [comment]
14.02.12

**Comment by estrada9166** [comment]
Can you try to reproduce the error [here](https://repl.it/@alejandroestrada/easygraphql-tester-issue) I had been trying but it's not possible

**Comment by overpod** [comment]
I have node js 11.12.0 and yarn. cannot be played on repl.it -- С уважениемТрофимов Алексейт. 8-913-679-26-84icq 260701263skype qwerpod   28.03.2019, 20:22, "Alejandro Estrada" <notifications@github.com>:Can you try to reproduce the error here I had been trying but it's not possible—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by estrada9166** [comment]
can you try to update GraphQL to `"^14.2.0"` I can't find the `v14.02.12`

**Comment by overpod** [comment]
Excuse me.I sealed with the version of GraphQLmy version 14.2.0 -- С уважениемТрофимов Алексейт. 8-913-679-26-84icq 260701263skype qwerpod   28.03.2019, 21:31, "Alejandro Estrada" <notifications@github.com>:can you try to update GraphQL to "^14.2.0" I can't find the v14.02.12—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by estrada9166** [comment]
I had been trying to reproduce it but it's not possible, I tried locally with `node v11.12.0` and yarn but there was no error... can you create a [repl.it](https://repl.it) or [codesandbox](https://codesandbox.io) with the exact same code and dependencies that you are testing (if it's possible)?

**Comment by overpod** [comment]
I have a problem in the project.
Different packages have different graphql versions.
Sorry

**Comment by overpod** [comment]
you have a great product

**Comment by estrada9166** [comment]
Thank you so much! I'm glad it's useful 😀

I'm going to close this issue.

**Comment by overpod** [comment]
Yes. thanks for the help
